baseURL = "https://altinn.github.io/docs/"
languageCode = "nb"
defaultContentLanguage = "nb"

contentDir = "content"
staticDir = "static"
publishDir = "public"

title = "Altinn docs"
theme = "hugo-theme-altinn"
metadataFormat = "yaml"
pluralizeListTitles = false
preservetaxonomynames = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["RSS"] # page home section taxonomy taxonomyTerm RSS sitemap robotsTXT 404

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"

[markup.tableOfContents]
startLevel = 2
endLevel = 2
ordered = false

[blackfriday]
fractions = false # disable automatic fraction rendering

[params]
editURL = "https://github.com/altinn/docs/blob/master/content/"
noHomeIcon = true # default is false
noSearch = false # default is false
disableNavChevron = false
showVisitedLinks = false # default is false
# themeVariant = "gray" # choose theme variant "gray" for systemdocumentation, like Altinnpedia. Blue theme is for altinndigitalisering.

[outputs]
home = ["HTML", "JSON"] # JSON generates index.json file used by search

[related]
includeNewer = true # Excluding newer content is not relevant for our site.
threshold = 80 # Range 0-100 
toLower = false
[[related.indices]]
name = 'keywords'
weight = 100
toLower = true
[[related.indices]]
name = 'tags' # Tags are included by default with weight 80, as long as tags are set up as a taxonomy.
weight = 80
